name: Claude Assistant
  on:
    issue_comment:
      types: [created]
  permissions:
    contents: write
    issues: write
    pull-requests: write

  jobs:
    claude-response:
      runs-on: ubuntu-latest
      steps:
        - uses: anthropics/claude-code-action@beta
          with:
            claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
            github_token: ${{ secrets.GITHUB_TOKEN }}
